### ISSUE TITLE
Support for Ruby2.7?

### ISSUE THREAD

**Issue by utkarsh2102** [aquasync/ruby-ole#26]
Hi there,

Thank you for your amazing work on ruby-ole.
However, while building it against Ruby2.7, the tests seem to be failing.
Here are the logs:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│ Run tests for ruby2.5 from debian/ruby-test-files.yaml                       │
└──────────────────────────────────────────────────────────────────────────────┘

RUBYLIB=/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby:. GEM_PATH=/<<PKGBUILDDIR>>/debian/ruby-ole/usr/share/rubygems-integration/all:/var/lib/gems/2.5.0:/usr/lib/ruby/gems/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0 ruby2.5 -ryaml -e YAML.load_file\(\"debian/ruby-test-files.yaml\"\).each\ \{\ \|f\|\ require\ f\ \}
Loaded suite -e
Started
...............................................................................
.
Finished in 0.174469705 seconds.
-------------------------------------------------------------------------------
80 tests, 306 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------
458.53 tests/s, 1753.89 assertions/s
/usr/bin/ruby2.7 /usr/bin/gem2deb-test-runner

┌──────────────────────────────────────────────────────────────────────────────┐
│ Run tests for ruby2.7 from debian/ruby-test-files.yaml                       │
└──────────────────────────────────────────────────────────────────────────────┘

RUBYLIB=/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby:. GEM_PATH=/<<PKGBUILDDIR>>/debian/ruby-ole/usr/share/rubygems-integration/all:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0 ruby2.7 -ryaml -e YAML.load_file\(\"debian/ruby-test-files.yaml\"\).each\ \{\ \|f\|\ require\ f\ \}
/<<PKGBUILDDIR>>/lib/ole/support.rb:170: warning: already initialized constant Ole::IOMode::Constants::BINARY
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/support.rb:170: warning: previous definition of BINARY was here
/<<PKGBUILDDIR>>/lib/ole/support.rb:174: warning: already initialized constant Ole::IOMode::NAMES
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/support.rb:174: warning: previous definition of NAMES was here
/<<PKGBUILDDIR>>/lib/ole/storage/version.rb:5: warning: already initialized constant Ole::Storage::VERSION
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/storage/version.rb:5: warning: previous definition of VERSION was here
/<<PKGBUILDDIR>>/lib/ole/base.rb:8: warning: already initialized constant Ole::Log
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/base.rb:8: warning: previous definition of Log was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:54: warning: already initialized constant Ole::Types::Lpwstr::FROM_UTF16
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:54: warning: previous definition of FROM_UTF16 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:55: warning: already initialized constant Ole::Types::Lpwstr::TO_UTF16
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:55: warning: previous definition of TO_UTF16 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:91: warning: already initialized constant Ole::Types::FileTime::SIZE
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:91: warning: previous definition of SIZE was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:119: warning: already initialized constant Ole::Types::FileTime::EPOCH
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:119: warning: previous definition of EPOCH was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:169: warning: already initialized constant Ole::Types::Clsid::SIZE
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:169: warning: previous definition of SIZE was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:170: warning: already initialized constant Ole::Types::Clsid::PACK
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:170: warning: previous definition of PACK was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:224: warning: already initialized constant Ole::Types::Variant::NAMES
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:224: warning: previous definition of NAMES was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:273: warning: already initialized constant Ole::Types::Variant::CLASS_MAP
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:273: warning: previous definition of CLASS_MAP was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_EMPTY
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_EMPTY was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_NULL
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_NULL was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_I2
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_I2 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_I4
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_I4 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_R4
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_R4 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_R8
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_R8 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_CY
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_CY was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_DATE
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_DATE was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_BSTR
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_BSTR was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_DISPATCH
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_DISPATCH was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_ERROR
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_ERROR was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_BOOL
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_BOOL was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_VARIANT
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_VARIANT was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_UNKNOWN
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_UNKNOWN was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_DECIMAL
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_DECIMAL was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_I1
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_I1 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_UI1
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_UI1 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_UI2
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_UI2 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_UI4
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_UI4 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_I8
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_I8 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_UI8
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_UI8 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_INT
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_INT was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_UINT
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_UINT was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_VOID
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_VOID was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_HRESULT
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_HRESULT was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_PTR
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_PTR was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_SAFEARRAY
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_SAFEARRAY was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_CARRAY
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_CARRAY was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_USERDEFINED
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_USERDEFINED was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_LPSTR
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_LPSTR was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_LPWSTR
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_LPWSTR was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_FILETIME
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_FILETIME was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_BLOB
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_BLOB was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_STREAM
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_STREAM was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_STORAGE
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_STORAGE was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_STREAMED_OBJECT
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_STREAMED_OBJECT was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_STORED_OBJECT
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_STORED_OBJECT was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_BLOB_OBJECT
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_BLOB_OBJECT was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_CF
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_CF was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_CLSID
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_CLSID was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_ILLEGALMASKED
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_ILLEGALMASKED was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_VECTOR
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_VECTOR was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_ARRAY
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_ARRAY was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_BYREF
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_BYREF was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_RESERVED
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_RESERVED was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:283: warning: already initialized constant Ole::Types::Variant::Constants::VT_ILLEGAL
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:283: warning: previous definition of VT_ILLEGAL was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:287: warning: already initialized constant Ole::Types::Variant::Constants::VT_TYPEMASK
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:287: warning: previous definition of VT_TYPEMASK was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:313: warning: already initialized constant Ole::Types::FROM_UTF16
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:313: warning: previous definition of FROM_UTF16 was here
/<<PKGBUILDDIR>>/lib/ole/types/base.rb:314: warning: already initialized constant Ole::Types::TO_UTF16
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/base.rb:314: warning: previous definition of TO_UTF16 was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:15: warning: already initialized constant Ole::Types::PropertySet::HEADER_SIZE
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:15: warning: previous definition of HEADER_SIZE was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:16: warning: already initialized constant Ole::Types::PropertySet::HEADER_PACK
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:16: warning: previous definition of HEADER_PACK was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:17: warning: already initialized constant Ole::Types::PropertySet::OS_MAP
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:17: warning: previous definition of OS_MAP was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:25: warning: already initialized constant Ole::Types::PropertySet::DATA
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:25: warning: previous definition of DATA was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:66: warning: already initialized constant Ole::Types::PropertySet::PROPERTY_MAP
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:66: warning: previous definition of PROPERTY_MAP was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:71: warning: already initialized constant Ole::Types::PropertySet::Constants::FMTID_SummaryInformation
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:71: warning: previous definition of FMTID_SummaryInformation was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:71: warning: already initialized constant Ole::Types::PropertySet::Constants::FMTID_DocSummaryInfo
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:71: warning: previous definition of FMTID_DocSummaryInfo was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:71: warning: already initialized constant Ole::Types::PropertySet::Constants::FMTID_UserDefinedProperties
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:71: warning: previous definition of FMTID_UserDefinedProperties was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:81: warning: already initialized constant Ole::Types::PropertySet::Section::SIZE
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:81: warning: previous definition of SIZE was here
/<<PKGBUILDDIR>>/lib/ole/types/property_set.rb:82: warning: already initialized constant Ole::Types::PropertySet::Section::PACK
/<<PKGBUILDDIR>>/debian/ruby-ole/usr/lib/ruby/vendor_ruby/ole/types/property_set.rb:82: warning: previous definition of PACK was here
/<<PKGBUILDDIR>>/lib/ole/storage/base.rb:352:in `<class:Storage>': superclass mismatch for class Header (TypeError)
	from /<<PKGBUILDDIR>>/lib/ole/storage/base.rb:21:in `<module:Ole>'
	from /<<PKGBUILDDIR>>/lib/ole/storage/base.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /<<PKGBUILDDIR>>/lib/ole/storage.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /<<PKGBUILDDIR>>/test/test_filesystem.rb:27:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from -e:1:in `block in <main>'
	from -e:1:in `each'
	from -e:1:in `<main>'
ERROR: Test "ruby2.7" failed. Exiting.
```

Could you perhaps take a look at help us figure this out?

**Comment by aquasync** [comment]
All those warnings and even the final failure are the result of including a file twice; the error comes from a class deriving from Struct, which gives a different superclass on the second inclusion.

As to why that's happening, seems there are two copies of the library from the warnings - one in /lib/, and another in /debian/ruby-ole/usr/lib/ruby/vendor_ruby/. The vendored copy I'd guess is using local requires or something but hasn't moved the modules into a separate namespace so chokes when another copy is loaded.

I don't have 2.7 so can't test at the moment, but are you able to just run the tests directly with 2.7? What's the package that is being built?

**Comment by aquasync** [comment]
I guess it is something to do with the manipulation of the load path at the top of the test files. I put it there to always use the co-located code when running tests; when doing local dev work I want it to use the code I'm working on, when installed in a gem or package it would use that code.

It could (and maybe should?) probably be changed to do that manipulation via say the rake task. Not sure what standard practice is here. That code has been in the tests for over a decade though, and can't figure out what has changed in ruby 2.7 that would make it a problem.

**Comment by aquasync** [comment]
Running `rake test` on ruby 2.7 works without error, so I'm going to assume this is some interaction between the load path manipulation in the tests and `gem2deb-test-runner`.
